### ISSUE TITLE
Binding to non-defined function `+boy/unfill-paragraph`

### ISSUE THREAD

**Issue by dfrib** [UndeadKernel/emacs_doom_private#1]
As a non-evil user just getting start with DOOM Emacs, thanks a lot for your nice non-evil configuration of DOOM Emacs!

---

In `+bindings.el` the binding `C-M-q` seems to refer to a target function that is never defined.
```
"C-M-q"         #'+boy/unfill-paragraph
```

**Comment by dfrib** [comment]
I realize the reason I could not find the definition of the function was that I had removed the `autoload/boy.el` file on my fork, so not so surprisingly that the binding was dead. Closing this, sorry for the confusion!

**Comment by UndeadKernel** [comment]
I'm happy that my configuration is helping you get started. Feel free to ask any questions here. You can also message me in Doom's Discord server.

**Comment by dfrib** [comment]
@UndeadKernel thanks, will do! Using a top-down approach from your config proved much easier than starting from scratch/a bottom-up one.
